export interface Seri {
    totalCount: number
    count: number
    data: SeriData[]
}

export interface SeriData {
    studyId: string
    testTypeId: string
    barcode: string
    registeredAt: string
    seriInstances: number
    seriResults: number
    resultStatus: number
    isAutoGenerated: boolean
    study: SeriStudy
    testType: SeriTestType
    instances: SeriInstance[]
    id: string
    createdAt: string
    modifiedAt: string
}

export interface SeriStudy {
    customerId: string
    code: string
    patientId: string
    patientName: string
    patientSex: string
    diagnose: string
    barcode: string
    registeredAt: string
    studySeries: number
    seriesHasResult: number
    studyInstances: number
    studyResults: number
    resultStatus: number
    isAutoGenerated: boolean
    series: any[]
    id: string
    createdAt: string
    modifiedAt: string
}

export interface SeriTestType {
    customerId: string
    name: string
    code: string
    desc: string
    id: string
    createdAt: string
    modifiedAt: string
    modifiedBy: string
}

export interface SeriInstance {
    studyId: string
    seriId: string
    testTypeId: string
    standardTestId: string
    barcode: string
    registeredAt: string
    resultStatus: number
    id: string
    createdAt: string
    modifiedAt: string
}
