export enum ControlType {
    Text = 'text',
    DateTime = 'datetime',
    Number = 'number',
    Checkbox = 'checkbox',
    TextArea = 'textarea',
    Combobox = 'combobox',
    RefInfo = 'refinfo',
    ColorPicker = 'colorpicker',
    Currency = 'currency',
    Percent = 'percent',
    Dynamic = 'dynamic',
    Autocomplete = 'autocomplete',
    Combotree = 'combotree',
}